/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplosql;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estudios
 */
public class NuevoCampo extends javax.swing.JFrame {

    public static String nombres = "", sentenciaC = "", sentenciaPK = "", sentenciaT = "";
    int i = 0;
    int conta = 0;
    int conta2 = 0;

    static DefaultTableModel modelo = new DefaultTableModel();
    boolean error = false;

    /**
     * Creates new form NuevoCampo
     */
    public NuevoCampo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nombreCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkBoxPK = new javax.swing.JCheckBox();
        checkBoxNNull = new javax.swing.JCheckBox();
        checkBoxUnique = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        tipoCampo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");

        checkBoxPK.setText("Primary key");

        checkBoxNNull.setText("Not Null");

        checkBoxUnique.setText("Unique");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tipoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTEGER", "TEXT" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkBoxPK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(checkBoxUnique, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBoxNNull, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(tipoCampo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxPK)
                .addGap(18, 18, 18)
                .addComponent(checkBoxNNull)
                .addGap(18, 18, 18)
                .addComponent(checkBoxUnique)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (i = 0; i < CreacionDeTabla.tablaCreacion.getColumnCount(); i++) {
            nombres = nombres + "\nUsado: " + CreacionDeTabla.tablaCreacion.getColumnName(i);

            if (NuevoCampo.nombreCampo.getText().equalsIgnoreCase(CreacionDeTabla.tablaCreacion.getColumnName(i).toString()) == true) {
                error = true;
            }

        }
        if (error == true) {
            JOptionPane.showMessageDialog(null, "Nombre de campo ya usado\n\nUse uno diferente de los siguientes\n" + nombres);
            nombres = "";
            error = false;
        } else {
            if (conta == 0) {
                sentenciaT = NuevoCampo.nombreCampo.getText() + " " + NuevoCampo.tipoCampo.getSelectedItem().toString() + " ";

            }
            if (conta >= 1) {
                sentenciaT = NuevoCampo.nombreCampo.getText() + " " + NuevoCampo.tipoCampo.getSelectedItem().toString();
            }
            if (NuevoCampo.checkBoxNNull.isSelected() == true) {
                sentenciaC = sentenciaC + " NOT NULL ";
            }
            if (NuevoCampo.checkBoxUnique.isSelected() == true) {
                sentenciaC = sentenciaC + " UNIQUE ";
            }
            if (NuevoCampo.checkBoxPK.isSelected() == true) {
                
//                    sentenciaPK = sentenciaPK + " PRIMARY KEY ";
                    
                
                if (conta2 == 0) {
                    sentenciaPK = sentenciaPK + NuevoCampo.nombreCampo.getText();
                    conta2++;
                } else {
                    sentenciaPK = sentenciaPK + "," + NuevoCampo.nombreCampo.getText();
                }
            }
            modelo.addColumn(NuevoCampo.nombreCampo.getText());
            CreacionDeTabla.tablaCreacion.setModel(modelo);
            this.setVisible(false);

            NuevoCampo.checkBoxNNull.setSelected(false);
            NuevoCampo.checkBoxUnique.setSelected(false);
            NuevoCampo.checkBoxPK.setSelected(false);
            nombres = "";
            i = 0;
            error = false;
            if (conta == 0) {
                Metodos.sentenciaF =sentenciaT + sentenciaC;
            } else {
                Metodos.sentenciaF = Metodos.sentenciaF + "," + sentenciaT + sentenciaC;
            }

        }
        conta++;
        sentenciaC = "";
        sentenciaT = "";
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox checkBoxNNull;
    public static javax.swing.JCheckBox checkBoxPK;
    public static javax.swing.JCheckBox checkBoxUnique;
    public static javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField nombreCampo;
    public static javax.swing.JComboBox<String> tipoCampo;
    // End of variables declaration//GEN-END:variables
}
